import { BrandMark, BookingSection, BusinessHours, CoverMedia, Differentials, Faq, Footer, Gallery, hasSection, Instagram, Location, MobileBookingCta, PrimaryCta, Process, ProfessionalList, ServiceList, Testimonials } from "../../shared";
import type { PublicTemplateProps } from "../../types";
import styles from "./styles.module.css";

export function BotanicalRitualTemplate(props: PublicTemplateProps){const{business,config,services,professionals,businessHours,booking}=props;const name=config.content.businessName||business.name;const sections:Record<string,React.ReactNode>={
hero:<section className={styles.hero} key="hero"><div className={styles.orb}><CoverMedia config={config} name={name}/></div><div className={styles.heroCopy}><span>Respire · cuide · renove</span><h1>{config.content.heroTitle}</h1><p>{config.content.heroSubtitle}</p><PrimaryCta config={config}/></div></section>,
positioning:config.content.introduction?<section className={styles.philosophy} key="positioning"><span>Nossa filosofia</span><p>{config.content.introduction}</p></section>:null,story:config.content.story?<section className={styles.philosophy} key="story"><span>Nossa história</span><p>{config.content.story}</p></section>:null,
differentials:<div className={styles.benefits} key="differentials"><Differentials config={config} title="Cuidado que respeita seu ritmo"/></div>,
services:<section className={styles.treatments} id="servicos" key="services"><ServiceList services={services} title="Tratamentos e rituais" variant="rituals"/></section>,
process:<div className={styles.process} key="process"><Process config={config}/></div>,
professionals:<section className={styles.team} id="equipe" key="professionals"><ProfessionalList professionals={professionals} services={services} config={config} variant="organic"/></section>,
testimonials:<div className={styles.quotes} key="testimonials"><Testimonials config={config}/></div>,faq:<div className={styles.quotes} key="faq"><Faq config={config}/></div>,gallery:<div className={styles.gallery} key="gallery"><Gallery config={config} variant="organic"/></div>,
booking:<div className={styles.booking} key="booking"><BookingSection config={config} booking={booking} tone="sage"/></div>,businessHours:<div className={styles.info} key="businessHours"><BusinessHours businessHours={businessHours}/></div>,location:<div className={styles.info} key="location"><Location business={business} config={config}/></div>,instagram:<div className={styles.instagram} key="instagram"><Instagram config={config}/></div>,footer:<Footer business={business} config={config} key="footer"/>};return <main className={styles.page} id="top"><header className={styles.nav}><a href="#top"><BrandMark config={config} name={name}/><strong>{name}</strong></a><nav><a href="#servicos">Rituais</a><a href="#equipe">Terapeutas</a></nav><PrimaryCta config={config} compact/></header>{props.preview&&<div className="preview-ribbon">Prévia do rascunho · clientes não veem estas alterações</div>}{config.sections.filter(s=>s.visible).map(s=>sections[s.id])}{hasSection(config,"booking")&&<MobileBookingCta config={config}/>}</main>}
