import { CheckCircle2 } from "lucide-react";
import { BrandMark, BookingSection, BusinessHours, CoverMedia, Differentials, Faq, Footer, Gallery, hasSection, Instagram, Location, MobileBookingCta, PrimaryCta, Process, ProfessionalList, ServiceList, Testimonials } from "../../shared";
import type { PublicTemplateProps } from "../../types";
import styles from "./styles.module.css";

export function ClinicalLuxeTemplate(props:PublicTemplateProps){const{business,config,services,professionals,businessHours,booking}=props;const name=config.content.businessName||business.name;const sections:Record<string,React.ReactNode>={
hero:<section className={styles.hero} key="hero"><div className={styles.heroCopy}><span>Cuidado preciso. Decisões claras.</span><h1>{config.content.heroTitle}</h1><p>{config.content.heroSubtitle}</p><PrimaryCta config={config}/></div><div className={styles.heroMedia}><CoverMedia config={config} name={name}/></div></section>,
positioning:<section className={styles.trust} key="positioning"><div><CheckCircle2/><span>Agendamento online</span></div>{professionals.length>0&&<div><CheckCircle2/><span>{professionals.length} {professionals.length===1?"especialista":"especialistas"} disponível{professionals.length===1?"":"is"}</span></div>}{businessHours.length>0&&<div><CheckCircle2/><span>Horários atualizados</span></div>}</section>,story:config.content.story?<section className={styles.differentials} key="story"><span>Nossa história</span><h2>{config.content.story}</h2></section>:null,
process:<div className={styles.process} key="process"><Process config={config}/></div>,services:<section className={styles.procedures} id="servicos" key="services"><ServiceList services={services} title="Procedimentos" variant="clinical"/></section>,differentials:<div className={styles.differentials} key="differentials"><Differentials config={config} title="Segurança em cada etapa"/></div>,
professionals:<section className={styles.specialists} id="equipe" key="professionals"><ProfessionalList professionals={professionals} services={services} config={config} variant="specialists"/></section>,testimonials:<div className={styles.testimonials} key="testimonials"><Testimonials config={config}/></div>,faq:<div className={styles.faq} id="duvidas" key="faq"><Faq config={config}/></div>,gallery:<div className={styles.testimonials} key="gallery"><Gallery config={config} variant="lookbook"/></div>,instagram:<div className={styles.info} key="instagram"><Instagram config={config}/></div>,booking:<div className={styles.booking} key="booking"><BookingSection config={config} booking={booking} tone="clinical"/></div>,businessHours:<div className={styles.info} key="businessHours"><BusinessHours businessHours={businessHours}/></div>,location:<div className={styles.info} key="location"><Location business={business} config={config}/></div>,footer:<Footer business={business} config={config} key="footer"/>};return <main className={styles.page} id="top"><header className={styles.nav}><a href="#top"><BrandMark config={config} name={name}/><strong>{name}</strong></a><nav><a href="#servicos">Procedimentos</a><a href="#equipe">Especialistas</a><a href="#duvidas">Dúvidas</a></nav><PrimaryCta config={config} compact/></header>{props.preview&&<div className="preview-ribbon">Prévia do rascunho · clientes não veem estas alterações</div>}{config.sections.filter(s=>s.visible).map(s=>sections[s.id])}{hasSection(config,"booking")&&<MobileBookingCta config={config}/>}</main>}
